// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");
var Component2$ReactHooksTemplate = require("./Component2.bs.js");

ReactDOMRe.renderToElementWithId(React.createElement(Component2$ReactHooksTemplate.make, {
          greeting: "x"
        }), "index2");

/*  Not a pure module */
